// Drizzle schema. Better Auth tables (users, sessions, accounts, verifications)
// are generated by `bun x @better-auth/cli generate` against this file once
// the Better Auth config is wired in apps/api.
//
// Domain tables (docs, revisions, comments, suggestions, doc_collaborators)
// land here as the implementation begins. See CONTEXT.md for the domain
// glossary and ADR-0004 / ADR-0005 for the storage shape.

import { pgTable, text, timestamp } from "drizzle-orm/pg-core";

// Placeholder until Better Auth schema is generated.
export const placeholder = pgTable("placeholder", {
  id: text("id").primaryKey(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});
